# Generated by Django 4.2.16 on 2024-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmarket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.IntegerField(default=0),
        ),
    ]
