# Generated by Django 4.2.16 on 2024-10-24 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carmarket", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField(max_length=4)),
                ("generation", models.CharField(max_length=50)),
                ("price", models.IntegerField(max_length=20)),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sedan"),
                            (1, "Hatchback"),
                            (2, "Universal"),
                            (3, "Coupe"),
                            (4, "SUV"),
                            (5, "Crossover"),
                            (6, "Minivan"),
                            (7, "Pickup"),
                            (8, "Cabriolet"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "fuel_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Petrol"),
                            (1, "Diesel"),
                            (2, "Electric"),
                            (3, "Hybrid"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "transmission",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Manual"), (1, "Automatic"), (2, "Robot")],
                        default=0,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/cars/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "car",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="carmarket.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cars",
                    models.ManyToManyField(
                        related_name="favorited_by", to="carmarket.car"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cars",
            name="favorites",
        ),
        migrations.RemoveField(
            model_name="favorites",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="contactseller",
            options={
                "verbose_name": "ContactSeller",
                "verbose_name_plural": "ContactsSeller",
            },
        ),
        migrations.AddField(
            model_name="contactseller",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactseller",
            name="message",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="Cards",
        ),
        migrations.DeleteModel(
            name="Cars",
        ),
        migrations.DeleteModel(
            name="Favorites",
        ),
        migrations.AddField(
            model_name="car",
            name="favorites",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="carmarket.favorite"
            ),
        ),
        migrations.AddField(
            model_name="contactseller",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="carmarket.car",
            ),
        ),
    ]
