# Generated by Django 4.2.16 on 2024-11-01 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmarket", "0002_car_card_favorite_remove_cars_favorites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="order_number",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
