# Generated by Django 4.2.16 on 2024-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmarket", "0002_car_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, default="default_car.png", null=True, upload_to="img/cars/"
            ),
        ),
    ]
