# Generated by Django 4.2.16 on 2024-11-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmarket", "0003_card_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="favorites",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="carmarket.favorite",
            ),
        ),
    ]
