# Generated by Django 4.2.16 on 2024-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmarket", "0003_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_car.png",
                null=True,
                upload_to="media/img/cars/",
            ),
        ),
    ]
