# Generated by Django 4.2.16 on 2024-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmarket", "0005_alter_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="seller_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="seller_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
