# Generated by Django 4.2.16 on 2024-11-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
    ]
